# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-10"

[[extensions]]
type = "ui_extension"
name = "icon-banner"
handle = "icon-banner"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "icon_title_1"
type = "single_line_text_field"
name = "Icon Title 1"

[[extensions.settings.fields]]
key = "icon_1"
type = "single_line_text_field"
name = "Icon"
description = "Choose from: verticalDots, warning, warningFill, store, success, truck, questionFill, return, reorder, plus, profile, question, mobile, pen, map, marker, minus, list, lock, magnify, horizontalDots, info, infoFill, grid, hamburger, hollowCircle, filter, geolocation, gift, error, errorFill, external, email, discount, disabled, delivery, delivered, delete, critical, close, clock, cart, calendar, camera, bag" 

[[extensions.settings.fields]]
key = "icon_title_2"
type = "single_line_text_field"
name = "Icon Title 2"

[[extensions.settings.fields]]
key = "icon_2"
type = "single_line_text_field"
name = "Icon 2"
description = "Choose from: verticalDots, warning, warningFill, store, success, truck, questionFill, return, reorder, plus, profile, question, mobile, pen, map, marker, minus, list, lock, magnify, horizontalDots, info, infoFill, grid, hamburger, hollowCircle, filter, geolocation, gift, error, errorFill, external, email, discount, disabled, delivery, delivered, delete, critical, close, clock, cart, calendar, camera, bag" 

[[extensions.settings.fields]]
key = "icon_title_3"
type = "single_line_text_field"
name = "Icon Title 3"

[[extensions.settings.fields]]
key = "icon_3"
type = "single_line_text_field"
name = "Icon 3"
description = "Choose from: verticalDots, warning, warningFill, store, success, truck, questionFill, return, reorder, plus, profile, question, mobile, pen, map, marker, minus, list, lock, magnify, horizontalDots, info, infoFill, grid, hamburger, hollowCircle, filter, geolocation, gift, error, errorFill, external, email, discount, disabled, delivery, delivered, delete, critical, close, clock, cart, calendar, camera, bag" 
